name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        run: |
          docker build --no-cache -t demorey/tur_region_bot:v1 .
          docker save -o tur_region_bot.tar demorey/tur_region_bot:v1

      - name: scp docker image to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          rm: true
          source: tur_region_bot.tar
          target: /docker_containers/tur_region_bot/build

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
                    cd /docker_containers/tur_region_bot
                    docker stop tur_region_bot
                    docker rm tur_region_bot
                    docker rmi demorey/tur_region_bot:v1
                    docker load -i ./build/tur_region_bot.tar
                    docker run -dit \
                    --name tur_region_bot \
                    --restart always \
                    -P \
                    -v ./logs:/tur_region_bot/logs \
                    -v ./data:/tur_region_bot/data \
                    demorey/tur_region_bot:v1
                    rm -rf build/
                  
